language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs"
before_install:
  - 'if [ "${TRAVIS_NODE_VERSION}" == "0.8" ] ; then npm install -g npm@2.6.1; fi'
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
